# Generated by Django 2.2.7 on 2019-11-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelWithUs', '0002_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='custEmail',
            field=models.EmailField(default='abc@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='customers',
            name='custPhone',
            field=models.IntegerField(default=1234567890),
        ),
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='destination',
            name='desc',
            field=models.TextField(max_length=500),
        ),
    ]
