# Generated by Django 2.2.7 on 2019-11-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelWithUs', '0003_auto_20191126_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='custFirstName',
            field=models.CharField(default='Test', max_length=100),
        ),
        migrations.AddField(
            model_name='customers',
            name='custLastName',
            field=models.CharField(default='Test', max_length=100),
        ),
    ]
